#!/usr/bin/env python3
"""
ivp_phase5.py — Dead Light Framework Tier 3 script.

Automated subset of IVP Phase 5 (Internal Consistency) checks. Covers the
mechanically-detectable parts of Phase 5:

    1. Numeric consistency — surface numeric tokens that appear multiple times
       across documents and flag where the same anchor-name has different values
       (e.g., "Council size 3-7" appearing as "Council size 5-7" elsewhere).
    2. Cross-file term occurrence — list each defined term and where it's used
       (helps reviewer spot term drift).
    3. Status/frontmatter consistency — already done by validate_frontmatter.py.
    4. README link integrity — already done by check_links.py.

The reasoning-heavy parts of Phase 5 (decision-to-doc reflection, policy
compliance per justification segment, equivalence between debate decisions
and phase docs) require LLM analysis and are NOT automated here.

Output: generates `framework/audit/findings-phase5-<date>.md` skeleton with
the mechanical findings prepopulated; reviewer fills in the reasoning-heavy
sections.

Usage:
    python scripts/ivp_phase5.py                # dry-run (preview output)
    python scripts/ivp_phase5.py --apply        # write findings-phase5-<date>.md

Authorised by debate 007.
"""
from __future__ import annotations

import re
from collections import defaultdict
from datetime import date
from pathlib import Path

import frontmatter
import typer

app = typer.Typer(add_completion=False, help=__doc__)


EXCLUDE_DIRS = {
    ".git",
    ".kiro",
    "node_modules",
    ".pytest_cache",
    "__pycache__",
    ".claude",
    "blogs",
    "distribution",  # distribution is a derived artifact; Phase 5 audits framework/ + case-studies/
    "scripts",
}

# Numeric-claim patterns to track. Each pattern includes:
#   - a label (the claim's canonical name)
#   - a regex that captures the numeric value
NUMERIC_PATTERNS = [
    ("Council size range", re.compile(r"Council size [^\n]*?(\d+[-–]\d+)\b")),
    ("Reckoning Team size range", re.compile(r"Reckoning Team[^\n]*?(\d+[-–]\d+)\b")),
    ("Laws cap", re.compile(r"(?:Laws|Immutable Laws)[^\n]*?(?:cap|maximum|hard cap)[^\n]*?(\d+)\b")),
    ("Stress-test divergence threshold", re.compile(r"divergence[^\n]*?([<>]?\s*\d+\s*%)")),
]


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def iter_markdown_files(root: Path, scope: list[str] | None = None) -> list[Path]:
    if scope:
        out: list[Path] = []
        for sub in scope:
            p = root / sub
            if p.exists():
                for f in p.rglob("*.md"):
                    if not any(part in EXCLUDE_DIRS for part in f.relative_to(root).parts):
                        out.append(f)
        return sorted(out)

    out = []
    for path in root.rglob("*.md"):
        if any(part in EXCLUDE_DIRS for part in path.relative_to(root).parts):
            continue
        out.append(path)
    return sorted(out)


def collect_numeric_claims(files: list[Path], root: Path) -> dict[str, dict[str, list[str]]]:
    """For each NUMERIC_PATTERN label, collect value -> [file:line] occurrences."""
    out: dict[str, dict[str, list[str]]] = {label: defaultdict(list) for label, _ in NUMERIC_PATTERNS}
    for file in files:
        try:
            text = file.read_text(encoding="utf-8")
        except Exception:  # noqa: BLE001
            continue
        for i, line in enumerate(text.splitlines(), start=1):
            for label, pattern in NUMERIC_PATTERNS:
                m = pattern.search(line)
                if m:
                    value = m.group(1).strip()
                    location = f"{file.relative_to(root)}:{i}"
                    out[label][value].append(location)
    return out


def render_findings(numeric: dict[str, dict[str, list[str]]], file_count: int, today_iso: str) -> str:
    lines: list[str] = [
        "---",
        f'title: "IVP Findings — Phase 5 (Internal Consistency) — {today_iso}"',
        "status: working",
        "version: not versioned",
        "audience: both",
        "type: audit",
        f"last_updated: {today_iso}",
        "supersedes: null",
        "sealed_by: null",
        "---",
        "",
        f"# IVP Findings — Phase 5 (Internal Consistency) — {today_iso}",
        "",
        "> **Status:** Phase 5 mechanical findings auto-generated by `scripts/ivp_phase5.py`. Reviewer fills in reasoning-heavy sections (decision-to-doc reflection, policy compliance, term-drift judgments) by hand.",
        "> **Auditor:** Claude Code (Opus 4.7) + automated checks via `scripts/ivp_phase5.py`.",
        "> **Mode:** Industry-pragmatic (per IVP spec v0.3 § 1).",
        f"> **Files scanned:** {file_count} markdown files under `framework/` + `case-studies/` (excluded: `distribution/`, `scripts/`, `.claude/`, `blogs/`, tooling dirs).",
        "",
        "---",
        "",
        "## 1. Executive verdict",
        "",
        "_(Fill in after reviewing the auto-detected findings below + completing the manual checks.)_",
        "",
        "---",
        "",
        "## 2. Auto-detected numeric consistency findings",
        "",
        "For each tracked anchor-name (Council size, Reckoning Team size, Laws cap, Stress-test divergence threshold), all numeric values found across the scanned docs are listed. **A label with multiple values is a candidate finding** — review whether the values legitimately differ by context or whether they're inconsistent.",
        "",
    ]

    any_multi = False
    for label, value_map in numeric.items():
        lines.append(f"### {label}")
        lines.append("")
        if not value_map:
            lines.append("_(No matches found.)_")
            lines.append("")
            continue
        if len(value_map) > 1:
            any_multi = True
            lines.append(f"**⚠ Multiple values detected ({len(value_map)} distinct):**")
            lines.append("")
        else:
            lines.append(f"Single consistent value: `{next(iter(value_map))}`")
            lines.append("")
        lines.append("| Value | Occurrences |")
        lines.append("|---|---|")
        for value, locs in sorted(value_map.items()):
            sample = " · ".join(locs[:5])
            extra = f" (+{len(locs) - 5} more)" if len(locs) > 5 else ""
            lines.append(f"| `{value}` | {sample}{extra} |")
        lines.append("")

    if any_multi:
        lines.append("> **Reviewer action:** for each anchor with multiple values above, decide whether the variance is legitimate (e.g., 'Laws cap 5-9' and 'Sector Laws cap 5-9' are the same value formatted differently) or a real inconsistency (e.g., '3-7' vs '5-7' for Council size — would be an F-NN finding).")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## 3. Manual checks (reviewer fills in)",
        "",
        "### Sub-check 1 — Term drift",
        "",
        "_(Run validate_frontmatter.py + check_links.py first to catch the mechanical issues. Then for each glossary term, list every non-defining occurrence and compare against the glossary definition. Flag scope shifts, role shifts, quietly added/removed attributes.)_",
        "",
        "### Sub-check 2 — Decision-to-doc reflection",
        "",
        "_(For each decided debate, verify each decision element is reflected in the relevant phase doc(s). Missing reflections are MEDIUM or HIGH depending on whether the decision is load-bearing.)_",
        "",
        "### Sub-check 3 — Policy compliance",
        "",
        "_(Re-check every justification segment against the three framework-wide policies: 40k naming-only, industry standards over framework arithmetic, practitioner voice. A justification resting on 40k metaphor or framework-internal arithmetic with no industry anchor is a CRITICAL finding.)_",
        "",
        "### Sub-check 4 — README link integrity",
        "",
        "_(Confirm `python scripts/check_links.py` output is empty or only known-limitation links; verify 'planned' links in README do not assert content; verify existing links resolve.)_",
        "",
        "---",
        "",
        "## 4. Findings table (reviewer fills in)",
        "",
        "| ID | Severity | Issue type | Locations | Detail |",
        "|---|---|---|---|---|",
        "| _F-NN_ | _CRITICAL / HIGH / MEDIUM / LOW_ | _term-drift / decision-to-doc / quantitative / policy / link_ | _file:line_ | _description_ |",
        "",
        "---",
        "",
        "## 5. Limitations of this audit (auto-generated portion)",
        "",
        "- This script automates Sub-check 3 (quantitative consistency) for a fixed set of NUMERIC_PATTERNS only. Other numeric claims in the docs require manual review.",
        "- Sub-checks 1, 2, and parts of 3-4 require LLM-level reasoning and are NOT automated.",
        "- Term-drift detection requires comparing semantics across contexts, not just text matching; deferred to manual review.",
        "- The script does not interpret the framework's own evolution (e.g., 'Council size 3-7' may legitimately appear as '≤ 5' historically before debate 004 raised it; these are CONTEXTUAL not inconsistencies).",
        "",
        "---",
        "",
        "## 6. Audit trail",
        "",
        f"- {today_iso}: `python scripts/ivp_phase5.py --apply` generated this skeleton.",
        "- _(reviewer adds entries as manual checks proceed)_",
    ])

    return "\n".join(lines) + "\n"


@app.command()
def main(
    apply: bool = typer.Option(False, "--apply", help="Write findings file (default: dry-run)."),
) -> None:
    """Run automated Phase 5 mechanical checks; emit findings skeleton."""
    root = repo_root()
    files = iter_markdown_files(root, scope=["framework", "case-studies"])
    typer.echo(f"Scanning {len(files)} markdown file(s) under framework/ + case-studies/ ...")

    numeric = collect_numeric_claims(files, root)

    today_iso = date.today().isoformat()
    output_path = root / "framework" / "audit" / f"findings-phase5-{today_iso}.md"
    content = render_findings(numeric, len(files), today_iso)

    if not apply:
        typer.echo(f"\n[DRY-RUN] Would write {len(content)} bytes to:")
        typer.echo(f"  {output_path.relative_to(root)}")
        typer.echo("")
        typer.echo("Auto-detected numeric findings (preview):")
        for label, value_map in numeric.items():
            marker = "⚠" if len(value_map) > 1 else "·"
            typer.echo(f"  {marker} {label}: {len(value_map)} distinct value(s)")
            for v, locs in sorted(value_map.items())[:3]:
                typer.echo(f"      {v!r}: {len(locs)} occurrence(s)")
        typer.echo("\n(Dry-run — pass --apply to write skeleton.)")
        raise typer.Exit(0)

    if output_path.exists():
        typer.echo(f"warning: {output_path.relative_to(root)} already exists; overwriting", err=True)

    output_path.write_text(content, encoding="utf-8")
    typer.echo(f"\n✓ Wrote {output_path.relative_to(root)} ({len(content)} bytes).")
    typer.echo("")
    typer.echo("Next: open the file and fill in the manual-check sections + findings table.")
    raise typer.Exit(0)


if __name__ == "__main__":
    app()
